### ISSUE TITLE
file upload tip

### ISSUE THREAD

**Issue by peidong-hu** [bigtester/automation-test-engine#101]
https://saucelabs.com/resources/selenium-file-upload

**Comment by peidong-hu** [comment]
we may only need to create a synonym in xsd to reuse sendkey action, elementfinder will be the same

**Comment by Jun-Yang** [comment]
Finished

**Comment by peidong-hu** [comment]
should it be better to change the xsd xml parameter 'datavalue' to 'fileNameWithAbsolutePath' for fileUpload action?

**Comment by Jun-Yang** [comment]
Parameter changed

**Comment by peidong-hu** [comment]
Yes. I have tested it. Working very well.
