### ISSUE TITLE
error when running bigtester demo script with Chrome driver on Linux 

### ISSUE THREAD

**Issue by peidong-hu** [bigtester/automation-test-engine#105]
Per the message, ATE on Linux is looking for Windows version chrome driver 'chromedriver.exe'
================================================================
<exception class="java.lang.IllegalStateException">
            <message>
              <![CDATA[The driver executable does not exist: /home/peidong/git/ate/automation-test-engine/automation-test-engine/org.bigtester.ate.core/browserdriver/liunx/googlechrome/64bit/chromedriver.exe]]>
            </message>
          </exception>

**Comment by Jun-Yang** [comment]
already fixed
