### ISSUE TITLE
step 2 in environment is not needed if the jre directory has been correctly set

### ISSUE THREAD

**Issue by peidong-hu** [bigtester/automation-test-engine#114]
I just tested on win7 32bits, step 2 in the environment setup procedure of quick user guide is not needed.  We need a 2nd person to validate this.

**Comment by Jun-Yang** [comment]
You are right. I have also tested on win7 32bits. We can delete step2. I will delete it. For the user who have installed jre, we can ask them to uninstall jre and reinstall jdk according to our procedure.
