### ISSUE TITLE
don't see Daisong's latest commit about elementfind xsd tag

### ISSUE THREAD

**Issue by peidong-hu** [bigtester/automation-test-engine#133]
Daisong might forget push since I was told that elementfind code which covers all the other elementfind tag in xsd had been checked in.

I can not find the commit on github.

Peidong

**Comment by peidong-hu** [comment]
It looks that Daisong's commit appears in the master. Is the issue caused by the wrong email address used to commit code in the first try?

**Comment by ericlu312** [comment]
Exactly, after I used the correct email address, the commit was added in the ATE .

Regards,
 
Eric Lu


Date: Thu, 7 May 2015 08:41:59 -0700

**Comment by peidong-hu** [comment]
Yes, you can close the issue now.

**Comment by Jun-Yang** [comment]
Finished
