### ISSUE TITLE
STS enviroment setting up error message when install TestNG

### ISSUE THREAD

**Issue by happygirlcici** [bigtester/automation-test-engine#197]
error message when I try to install TestNG

**Comment by happygirlcici** [comment]
![sts install error3](https://user-images.githubusercontent.com/22838588/29343499-6d561c88-81ff-11e7-8374-141fb9a71467.png)

**Comment by happygirlcici** [comment]
the button is gray, I can't install it

**Comment by bigtester-prot** [comment]
can u try expand the arrow beside the TestNG item in the middle panel of
the screen to see what children existing?

**Comment by happygirlcici** [comment]
fixed it

**Comment by peidong-hu** [comment]
Would be nice if you can add how u have fixed it, so others could learn
from you.

Thx
Peidong
