### ISSUE TITLE
Still have some red cross  in the left bar and some of xml file and main src dir can't open

### ISSUE THREAD

**Issue by happygirlcici** [bigtester/automation-test-engine#198]
![sts install error4](https://user-images.githubusercontent.com/22838588/29343854-d11e097c-8201-11e7-8cb1-138ab9862307.png)
![sts install error5](https://user-images.githubusercontent.com/22838588/29343911-365fc8f2-8202-11e7-87a6-56b8a5c2fc45.png)

**Comment by happygirlcici** [comment]
![sts install error5](https://user-images.githubusercontent.com/22838588/29343918-4556d896-8202-11e7-901a-28fdc7504e67.png)

**Comment by bigtester-prot** [comment]
Those red cross are expected. Don't need to be bothered by them.

The only red cross worries us is when you see them in folder src/java/main.

You can continue to setup your env according to the
https://github.com/bigtester/automation-test-engine/blob/master/org.bigtester.ate.core/README.codestyle
and
https://github.com/bigtester/automation-test-engine/blob/master/org.bigtester.ate.core/README.developer

Peidong

**Comment by bigtester-prot** [comment]
Sorry. the red cross in pom.xml may need to pay attention on though. But
please go through those steps in above two files before we tackle the
pom.xml issue.
