### ISSUE TITLE
indeedJobSearch JDK issue

### ISSUE THREAD

**Issue by happygirlcici** [bigtester/automation-test-engine#203]
-10:08:47.108 [org.bigtester.ate.TestProjectRunner.main()] ERROR o.b.ate.model.project.TestProject - 1771690144
 -java.lang.IllegalStateException: internal error at: JDK tools.jar is not correctly set in test environment. @Jun-Yang

**Comment by Jun-Yang** [comment]
Using the JRE in JDK directory, setting like the following picture:

![image 2](https://user-images.githubusercontent.com/8104900/29470806-cab5e070-841b-11e7-82cb-d3b6b5cf288e.png)
