### ISSUE TITLE
import ate master branch: BUILD FAILURE

### ISSUE THREAD

**Issue by stoneshaoipd9** [bigtester/automation-test-engine#204]
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project org.bigtester.ate.core: There are test failures.
[ERROR] 
[ERROR] Please refer to C:\Users\stone_000\git\ate\org.bigtester.ate.core\target\surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by bigtester-prot** [comment]
Those errors r expected. You just skip it. And continue to create a maven
install run configuration to skip the test and run the indeed job apply
test.

**Comment by stoneshaoipd9** [comment]
run configuration for indeed job apply test:
===============================================
    Default test
    Tests run: 1, Failures: 1, Skips: 0
===============================================


===============================================
Default suite
Total tests run: 1, Failures: 1, Skips: 0
===============================================

[TestNG] Time taken by org.testng.reporters.EmailableReporter2@3159c4b8: 51 ms
[TestNG] Time taken by org.testng.reporters.JUnitReportReporter@5649fd9b: 72 ms
[TestNG] Time taken by org.testng.reporters.SuiteHTMLReporter@6fd02e5: 666 ms
[TestNG] Time taken by [FailedReporter passed=0 failed=0 skipped=0]: 43 ms
[TestNG] Time taken by org.testng.reporters.jq.Main@31a5c39e: 290 ms
[TestNG] Time taken by org.testng.reporters.XMLReporter@4566e5bd: 45 ms
12:50:13.658 [Thread-1] INFO  o.s.c.s.GenericApplicationContext - Closing org.springframework.context.support.GenericApplicationContext@74d1dc36: startup date [Mon Aug 21 12:49:43 GMT-08:00 2017]; root of context hierarchy
12:50:13.663 [Thread-1] DEBUG o.s.b.f.s.DefaultListableBeanFactory - Returning cached instance of singleton bean 'stepUnexpectedAlertHandler'
12:50:13.665 [Thread-1] DEBUG o.s.b.f.s.DefaultListableBeanFactory - Returning cached instance of singleton bean 'multiWindowsHandler'
12:50:13.668 [Thread-1] DEBUG o.s.b.f.s.DefaultListableBeanFactory - Returning cached instance of singleton bean 'lifecycleProcessor'
12:50:13.670 [Thread-1] DEBUG o.s.b.f.s.DefaultListableBeanFactory - Destroying singletons in org.springframework.beans.factory.support.DefaultListableBeanFactory@655ef322: defining beans [org.springframework.aop.config.internalAutoProxyCreator,org.springframework.transaction.config.internalTransactionalEventListenerFactory,org.springframework.transaction.annotation.AnnotationTransactionAttributeSource#0,org.springframework.transaction.interceptor.TransactionInterceptor#0,org.springframework.transaction.config.internalTransactionAdvisor,org.springframework.context.annotation.internalConfigurationAnnotationProcessor,org.springframework.context.annotation.internalAutowiredAnnotationProcessor,org.springframework.context.annotation.internalRequiredAnnotationProcessor,org.springframework.context.annotation.internalCommonAnnotationProcessor,org.springframework.context.annotation.internalPersistenceAnnotationProcessor,org.springframework.context.event.internalEventListenerProcessor,org.springframework.context.event.internalEventListenerFactory,_DaoParent,elementInputDataDao,StepERDao,dataSource,entityManagerFactory,transactionManager,systemlogger,dbInitializer,globalUtilsForTestProject,baseATETest,org.bigtester.ate.model.project.XmlTestCase#0,suite01,testproject,baseERValue,myBasePageModel,myBasePageObject,baseElementAction,baseInputDataValue,org.bigtester.ate.model.data.CaseDataProcessor#0,org.bigtester.ate.model.casestep.JavaCodedStepBeanPostProcessor#0,org.bigtester.ate.model.data.CaseDataProcessor#1,org.bigtester.ate.model.page.elementaction.SendKeysActionPostBeanProcessor#0,org.bigtester.ate.model.page.elementfind.ElementFinderIndexOfSameProcessor#0,StepDataLogger,repeatStepExecutionLogger,globalUtilsForTestCase,stepUnexpectedAlertHandler,multiWindowsHandler,TestCaseLogger,TestStepResult,eadAssignValue,efTextArea,eaAssginValue,eadEnter,eaEnter,eadAssignValuePrepend,eaAssginValuePrepend,eadAssignValueAppend,eaAssginValueAppend,poLastPage,MyWebDriver2,stepLastStep,testcase,org.springframework.context.annotation.ConfigurationClassPostProcessor.importAwareProcessor,org.springframework.context.annotation.ConfigurationClassPostProcessor.enhancedConfigurationProcessor,eaEnter_SendKeysDataValueBean_ID,eaAssginValue_SendKeysDataValueBean_ID,eaAssginValuePrepend_SendKeysDataValueBean_ID,eaAssginValueAppend_SendKeysDataValueBean_ID]; root of factory hierarchy
12:50:13.706 [Thread-1] DEBUG o.s.b.f.s.DefaultListableBeanFactory - Retrieved dependent beans for bean 'multiWindowsHandler': [MyWebDriver2]
12:50:13.707 [Thread-1] DEBUG o.s.b.f.s.DefaultListableBeanFactory - Retrieved dependent beans for bean 'MyWebDriver2': [multiWindowsHandler, poLastPage]
12:50:13.707 [Thread-1] DEBUG o.s.b.f.s.DefaultListableBeanFactory - Retrieved dependent beans for bean 'poLastPage': [(inner bean)#2b08772d]
12:50:13.708 [Thread-1] DEBUG o.s.b.f.s.DefaultListableBeanFactory - Retrieved dependent beans for bean '(inner bean)#2b08772d': [testcase]
12:50:13.709 [Thread-1] DEBUG o.s.b.f.s.DefaultListableBeanFactory - Retrieved dependent beans for bean 'testcase': [(inner bean)#2b08772d]
12:50:13.711 [Thread-1] DEBUG o.s.b.f.s.DefaultListableBeanFactory - Retrieved dependent beans for bean '(inner bean)#346939bf#1': [suite01]
12:50:13.714 [Thread-1] DEBUG o.s.b.f.s.DisposableBeanAdapter - Invoking destroy() on bean with name 'entityManagerFactory'
12:50:13.714 [Thread-1] INFO  o.s.o.j.LocalContainerEntityManagerFactoryBean - Closing JPA EntityManagerFactory for persistence unit 'jpaData'
12:50:13.720 [Thread-1] DEBUG o.s.b.f.s.DefaultListableBeanFactory - Retrieved dependent beans for bean 'org.springframework.orm.jpa.vendor.HibernateJpaVendorAdapter#2cc3ad05': [entityManagerFactory]
