### ISSUE TITLE
Unit Test for elementAction ClickAction.java ClickActionTest.java-No bean named ... avaible

### ISSUE THREAD

**Issue by happygirlcici** [bigtester/automation-test-engine#210]
unit test-------ClickActionTest.java
org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'clickSignUp' available

package org.bigtester.ate.test.model.page.elementaction;

import org.bigtester.ate.GlobalUtils;
import org.bigtester.ate.model.page.atewebdriver.exception.BrowserUnexpectedException;
import org.bigtester.ate.model.page.elementaction.ClickAction;
import org.bigtester.ate.model.page.elementaction.DropdownListSelectAction;
import org.bigtester.ate.model.page.elementaction.ITestObjectAction;
import org.bigtester.ate.model.data.exception.RuntimeDataException;
import org.bigtester.ate.model.page.exception.PageValidationException;
import org.bigtester.ate.model.page.exception.StepExecutionException;
import org.bigtester.ate.model.page.page.MyWebElement;
import org.bigtester.ate.test.BigtesterProjectTest;
import org.openqa.selenium.By;
import org.openqa.selenium.By.ByXPath;
import org.openqa.selenium.support.ui.Select;
import org.springframework.test.context.ContextConfiguration;
import org.testng.Assert;
import org.testng.annotations.Test;

/**
 * 
 * @author Peidong Hu
 *
 */
@ContextConfiguration(locations = { "classpath:bigtesterTestNG/testSuite01/dropDownList.xml" })
public class ClickActionTest extends BigtesterProjectTest {

	@Test(priority = 1)
	public void mainTest() throws PageValidationException,
			RuntimeDataException, StepExecutionException, InterruptedException, BrowserUnexpectedException {
		getTestPage("bigtesterTestNG/aut/registration.html");

		MyWebElement<?> ead = (MyWebElement<?>) getApplicationContext()
				.getBean("clickSignUp");
		
		ead.doAction();

		Thread.sleep(3000);

		ITestObjectAction<?> testobj = (ITestObjectAction<?>) ead
				.getTestObjectAction();

		if (testobj == null) {
			Assert.assertTrue(false);
		} else {
			String selections = ((DropdownListSelectAction) GlobalUtils
					.getTargetObject(testobj)).getSelections();
			
			//String clickA = (ClickAction) GlobalUtils.getTargetObject(testobj).;

			
			ClickAction click = new ClickAction(myDriver);
			
			Select actualVal = new Select(getMyDriver().getWebDriverInstance()
					.findElements(new ByXPath("signUpButton")).get(0));

			Assert.assertTrue(click.equals(actualVal.getFirstSelectedOption().getText()));
			
		}

	}

}

**Comment by happygirlcici** [comment]
dropdownListHomePage.xml


<import resource="classpath:META-INF/page_base_bean.xml" />
	<import resource="classpath:META-INF/case_base_bean.xml" />
	<ate:htmlUnitDriver  />
	
	<ate:elementActionDef id="eadTestDropdownListSelect" elementFind="efDropdown" elementAction="eaSelect" />
	<ate:elementFindByTagName id="efDropdown"
		findByValue="select" />
	<ate:dropdownListSelectAction id="eaSelect"
		selections="Saab" />

**Comment by happygirlcici** [comment]
Why it is a xml ? but in the Test.java it is load page html
How to find our bean list? How to refresh bean name?

**Comment by bigtester-prot** [comment]
all good questions. Chenchen, you are going to the right path to get to
know what is Spring framework, And how to use it.

This way to learn things are called 'Problem Based Learning', which was
invented by Mcmaster University Medicine Discipline. It's very effective to
help the learner to quickly ramp up to an operational level.

Keep researching for your question.

**Comment by happygirlcici** [comment]
already fixed it , bean's name is not correct
