### ISSUE TITLE
can't upload apk to SauceLabs 

### ISSUE THREAD

**Issue by happygirlcici** [bigtester/automation-test-engine#233]
got error message

https://saucelabs.com/rest/v1/storage/:chencheninca

{
message: "API rate limit exceeded for public:10.240.75.165. See rate-limiting section in our API documentation."
}

**Comment by bigtester-prot** [comment]
https://wiki.saucelabs.com/display/DOCS/Rate+Limits+for+the+Sauce+Labs+REST+API

answer seems here

**Comment by happygirlcici** [comment]
ok

**Comment by happygirlcici** [comment]
https://app.testobject.com/#/chencheninca/apps/new/native
