### ISSUE TITLE
multi browser driver executables are currently packaged into ATE project

### ISSUE THREAD

**Issue by peidong-hu** [bigtester/automation-test-engine#42]
multi browser driver executables dependencies are currently packaged into ATE project. Need to research if possible that use pom.xml (maven) to manage them

**Comment by Jun-Yang** [comment]
Add plugging which can download browser dirver automatically

**Comment by peidong-hu** [comment]
My code checked in this morning might have issue causing firefox cannot be
started when run in mavan. Standalone java app execution has no problem.
