### ISSUE TITLE
clean up PMD warnings please

### ISSUE THREAD

**Issue by peidong-hu** [bigtester/automation-test-engine#45]
the classes under org.bigtester.ate.model.page.atewebdriver has lots of PMD warnings, 
I have give a instruction here, https://github.com/bigtester/automation-test-engine/blob/master/org.bigtester.ate.core/src/main/java/org/bigtester/ate/model/page/atewebdriver/EPlatform.java#L56 

You can refer to it to fix all the warnings in those classes

**Comment by Jun-Yang** [comment]
why I cannot see these warning? Did you change you configuration of PMD?

2015-01-21 0:23 GMT-05:00 peidong-hu <notifications@github.com>:

**Comment by peidong-hu** [comment]
There is a .pmd file at root folder of the project. Do u have it?

**Comment by Jun-Yang** [comment]
I didn't have. I solve the Jenkins running problem in Windows

2015-01-21 20:01 GMT-05:00 peidong-hu <notifications@github.com>:

> There is a .pmd file at root folder of the project. Do u have it?

**Comment by peidong-hu** [comment]
U can check out the latest code and see if you get the .pmd.

**Comment by Jun-Yang** [comment]
I got it. when I import again, I check 'clone submodule', now I have .pmd
file.

2015-01-22 5:44 GMT-05:00 peidong-hu <notifications@github.com>:

> U can check out the latest code and see if you get the .pmd.
