### ISSUE TITLE
multiple browser driver creation has hard coded the driver version in function createDriver()

### ISSUE THREAD

**Issue by peidong-hu** [bigtester/automation-test-engine#59]
multiple browser driver creation has hard coded the driver version in function createDriver(). This might cause error when the driver version upgraded in maven driver download plugin.

Changes need to be added to get the version number from maven driver download plugin config file. 

or directly read the whole driver path from the maven driver download plugin config file.

**Comment by Jun-Yang** [comment]
Finished
